version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  web:
    build:
      context: ./api_server
      args:
        - MYSQL_DATABASE=docker
        - MYSQL_USER=docker
        - MYSQL_PASSWORD=docker
        - MYSQL_HOST=db
    ports:
      - "8080:8080"
    links:
      - db
